### PR TITLE
update docker image name

### PR DESCRIPTION
**Pull request by mattdavis0351**
This PR gives the Docker image a more unique name to avoid conflict with other courses that rely on Docker images stored using packages

### CODE REVIEW

**Comment by brianamarie** [comment]
This change makes sense to me, @mattdavis0351! I trust that you've gone through and tested that it works - do you want someone else to verify this works as a part of the whole course? If not, I think this is good to 🚢!

**Comment by mattdavis0351** [comment]
@brianamarie @hectorsector I don't have an AWS account setup, could someone that does do a quick run through to make sure this naming change didn't hurt anything

**Comment by brianamarie** [comment]
> @brianamarie @hectorsector I don't have an AWS account setup, could someone that does do a quick run through to make sure this naming change didn't hurt anything

I can go through this on Thursday or Friday, but @hectorsector may be able to get to it sooner 😊

**Review by hectorsector — APPROVED** [review]
This is a simple enough fix, merging and I'm going through the course now anyway for other reasons.

**Pull request merged**
