### PR TITLE
Add Azure deployment

### PR DESCRIPTION
**Pull request by hectorsector**
This PR adds Azure as an option for deployment provider.

### CODE REVIEW

**Comment by brianamarie** [comment]
Yay! It says it isn't ready for review, but I'm excited to take it once it is 🎉

**Comment by hectorsector** [comment]
- [x] TODO: add validation to step 5 / PR 2: check that workflow is in the right path
- [ ] TODO: add validation to step 5 / PR 2: check that  `AZURE_WEBAPP_NAME: actions-ttt-deployment` contains the learner's name
- [x] TODO: check that stage label has been applied at step 6: Approve
- [x] TODO: recheck that no AWS steps were broken as a result of the changes

**Comment by hectorsector** [comment]
@mattdavis0351 @a-a-ron @brianamarie @lmkeston this PR is close! There's a list of [to do items](https://github.com/githubtraining/continuous-delivery/pull/23#issuecomment-587689317) that must be completed before this can go through some final reviews. I'll work on these but would appreciate any help you can provide!

**Comment by hectorsector** [comment]
I am working on moving the work from this branch into its own course. Stay tuned!

**Comment by mattdavis0351** [comment]
@hectorsector knowing there is a new course in the works surrounding this changes, does it makes sense to figure out the Google Cloud Platform piece for this course, or is there going to be good reason to wait and see what you come up with?

I doubt I'll get to the GCP side of things anytime soon, but it is on my mind.

**Comment by hectorsector** [comment]
Good question, @mattdavis0351. GCP is one of the reasons I thought it best to go ahead and create a new course altogether for Azure. It took quite a bit of work to make the current steps (written for AWS) generalized enough to also work for the Azure deployment. I can't imagine GCP making it much easier, so a separate course is one of the ways we can keep the logic mostly the same, but allow for changes that are cloud-specific. 

For now, the work in this PR has been moved [to its new repo](https://github.com/githubtraining/continuous-delivery-azure/) which I've verified is working. I'll close this PR out and will open an issue soon about how to test the new course and get it ready for publishing!

**Pull request closed without merging**
